from conversations.models import Message
m = Message(text="Welcome!", user_id=1, parent=m)
m.save()
  m1 = Message(text="How to", user_id=1, parent=m)
  m1.save()
    m2 = Message(text="Navigate", user_id=1, parent=m1)
    m2.save()
      m3 = Message(text="Zoom", user_id=1, parent=m2)
      m3.save()
        m4 = Message(text="Use two-finger or pinch zooming on a trackpad.", user_id=1, parent=m3)
        m4.save()
        m5 = Message(text="Use the icons in the top left to zoom in and out", user_id=1, parent=m3)
        m5.save()
      m6 = Message(text="Pan", user_id=1, parent=m2)
      m6.save()
        m7 = Message(text="Pan with three fingers on a Mac trackpad", user_id=1, parent=m6)
        m.save()
        m7 = Message(text="Click and drag to pan", user_id=1, parent=m6)
        m.save()
    m8 = Message(text="Post", user_id=1, parent=m)
    m8.save()
      m9 = Message(text="Click any message to reply to it.", user_id=1, parent=m8)
      m9.save()
        m10 = Message(text="You can click and drag the bottom right corner of the text box as you type your reply to change its size.", user_id=1, parent=m9)
        m10.save()
      m11 = Message(text="Create new conversations with the ''New Conversation'' button in the top left.", user_id=1, parent=m8)
      m11.save()
    m12 = Message(text="See replies", user_id=1, parent=m)
    m12.save()
      m13 = Message(text="The left bar shows conversations you're part of.", user_id=1, parent=m12)
      m13.save()
      m13 = Message(text="Click on a message in the tree to see its full contents.", user_id=1, parent=m12)
      m13.save()
      m13 = Message(text="Replies from different users have different border colors.", user_id=1, parent=m12)
      m13.save()
    m13 = Message(text="About", user_id=1, parent=m)
    m13.save()